import { ArrowLeft, ArrowRight, Banknote, Building2, CheckCircle2, ExternalLink, ShieldCheck, Store, Users } from 'lucide-react';

const plans = [
  {name:'食品営業賠償共済',lead:'必要な補償を、手頃な掛金で。',icon:Store,items:['食中毒など食品に起因する事故','基本的な対人・対物賠償'],note:'休業補償・従業員の傷害補償は特約で追加できます。'},
  {name:'あんしんフード君',lead:'お店で起きる幅広い事故に。',icon:Building2,items:['食品営業賠償共済の補償','店内でのお客さまの事故','施設が原因となる事故'],note:'休業補償・従業員の傷害補償は特約で追加できます。'},
  {name:'スーパーあんしんフード君',lead:'営業中から休業時まで、まとめて。',icon:Users,items:['あんしんフード君の補償','休業補償','従業員の傷害補償'],note:'現金盗難補償など、追加できる特約もあります。'},
];
const examples=[['従業員の傷害','支払例 86万円','https://drive.google.com/file/d/10uJzCfaEZB054lX5izdSCj_vPCcK_RhA/view?usp=drive_link'],['水漏れ事故','支払例 459万円','https://drive.google.com/file/d/10u43GPM2pOllB1lqfXLoE8LLonCQEhPp/view?usp=drive_link'],['現金盗難','支払例 38万円','https://drive.google.com/file/d/11GLUOPutI4VJH9DD-XuicloBEsAJ_Ps2/view?usp=sharing'],['ホテルのベッド破損','補償事例','https://drive.google.com/file/d/11C50k9uHf1fjmwWJ_fSoCz5oMknODDcT/view?usp=sharing']];

export default function InsurancePage(){return <main className="subpage insurance-page">
  <header className="site-header subpage-header"><a className="brand" href="/"><span className="brand-mark"><ShieldCheck size={24}/></span><span>八街市食品衛生連合会</span></a><nav aria-label="共済ページメニュー"><a href="#plans">プランの違い</a><a href="#examples">補償事例</a><a href="/payment">払込方法</a><a href="/faq">よくある質問</a></nav></header>
  <section className="subpage-hero insurance-hero"><div className="section-shell subpage-hero-inner"><a className="back-link" href="/"><ArrowLeft size={17}/>トップページへ戻る</a><p className="eyebrow">FOOD BUSINESS PROTECTION</p><h1>あんしん<br/>フード君</h1><p>食中毒や店内事故など、食品営業に関わるさまざまなリスクに備える共済制度です。</p></div></section>
  <section className="insurance-intro section-shell"><div><p className="section-label">ABOUT</p><h2>もしもの事故から、<br/>お店と働く人を守る。</h2></div><div><p>補償の範囲に合わせて、3つのプランから選べます。加入には食品衛生協会への入会が必要です。</p><div className="insurance-points"><span><CheckCircle2/>契約期間は1年間</span><span><CheckCircle2/>掛金入金確認後、1日または15日から開始</span></div></div></section>
  <section id="plans" className="plan-section"><div className="section-shell"><p className="section-label">PLAN</p><h2>3つのプラン</h2><div className="plan-grid">{plans.map(({name,lead,icon:Icon,items,note},index)=><article key={name} className={index===2?'recommended':''}><span className="plan-number">0{index+1}</span><Icon/><p className="plan-lead">{lead}</p><h3>{name}</h3><ul>{items.map(item=><li key={item}><CheckCircle2/>{item}</li>)}</ul><p className="plan-note">{note}</p></article>)}</div><p className="insurance-caution">実際の補償内容は、加入するプラン・特約・契約条件によって異なります。申込み前に最新のパンフレットと重要事項をご確認ください。</p></div></section>
  <section id="examples" className="example-section section-shell"><div className="section-heading"><div><p className="section-label">CASE STUDIES</p><h2>補償事例</h2></div><p>実際の事故をもとにした支払事例です。各資料は別画面で開きます。</p></div><div className="example-grid">{examples.map(([title,amount,href])=><a key={title} href={href} target="_blank" rel="noreferrer"><Banknote/><div><h3>{title}</h3><p>{amount}</p></div><ExternalLink/></a>)}</div></section>
  <section className="insurance-contact"><div className="section-shell insurance-contact-inner"><div><p className="section-label">CONTACT</p><h2>加入や事故のご相談</h2><p>印旛保健所管内食品衛生協会へお問い合わせください。</p><strong>043-483-1179</strong></div><div><a className="primary-button" href="https://www.n-shokuei.jp/kyousai/anshin_food.html" target="_blank" rel="noreferrer">公式情報を確認する<ExternalLink/></a><a className="secondary-button" href="/payment">賠償共済の払込方法<ArrowRight/></a></div></div></section>
  <footer><div className="section-shell footer-grid"><div><div className="brand footer-brand"><span className="brand-mark"><ShieldCheck size={24}/></span><span>八街市食品衛生連合会</span></div><p>地域の食の安全を、みなさまとともに。</p></div><div><h3>所在地</h3><p>〒289-1115<br/>八街市八街ほ224<br/>八街商工会議所内</p></div><div><h3>連絡先</h3><p>TEL 043-443-3021<br/>FAX 043-443-7221</p></div></div><div className="copyright">© Yachimata Food Hygiene Association</div></footer>
</main>}
